[package]
name = "virtual_can"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.6"
rand = "0.8"
rumqttc = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand_distr = "0.4"